corrijo algunos scripts de sync

diff --git a/sync/git b/sync/git
--- a/sync/git
+++ b/sync/git
@@ -2,53 +2,43 @@
 # git_sync.sh: actualiza proyectos versionados con git
 
 set -e
+
 project_root="/home/interior/udc-server-config"
 doc_root="/opt/lampp/htdocs"
 apache_user="daemon"
 status="${project_root}/www/status/gitsync.status"
-ERROR=0
 web_assets_source="/${project_root}/www/status"
 
-echo "Sincronización de proyectos Git" > $status
+salir() {
+  echo "ERROR: PROCESO GIT FALLIDO." | tee -a $status
+}
 
-echo "====== PROYECTO: server_config =====" >> $status
+trap salir ERR
+
+echo "" > $status
+
+echo "Sincronización de proyectos Git" | tee -a $status
+
+echo "====== PROYECTO: server_config =====" | tee -a $status
 cd ${project_root}
 git add .
+git stash save
 nice -n 20 time -f'Tiempo total de descarga: %E' git fetch >> $status 2>&1
-git log -1 >> $status 2>&1
+git log -1 | tee -a $status
 nice -n 20 git rebase origin >> $status 2>&1
-
-CODE=$?
-if [ $CODE != "0" ]; then
-echo "ERROR: falló la sincronización. Revise la salida del comando para solucionar el problema (error $CODE)." >> $status
-ERROR=1
-fi
 
 touch ${project_root}/www/status/datasync.status
 touch ${project_root}/www/status/gitsync.status
 touch ${project_root}/www/status/mysql_replication.status
 
-CODE=$?
-if [ $CODE != "0" ]; then
-echo "ERROR: falló la sincronización. Revise la salida del comando para solucionar el problema (error $CODE)." >> $status
-ERROR=1
-fi
-
-echo "====== PROYECTO: moodle_interior =====" >> $status
+echo "====== PROYECTO: moodle_interior =====" | tee -a $status
 cd ${doc_root}/moodle
 git add .
+git stash save
 nice -n 20 git reset --hard >> $status 2>&1
 nice -n 20 time -f'Tiempo total de descarga: %E' git fetch >> $status 2>&1
 nice -n 20 git reset --hard >> $status 2>&1
 nice -n 20 git rebase origin/master >> $status 2>&1
-git log -1 >> $status 2>&1
+git log -1 | tee -a $status
 
-CODE=$?
-if [ $CODE != "0" ]; then
-echo "ERROR: falló la sincronización. Revise la salida del comando para solucionar el problema (error $CODE)." >> $status
-ERROR=1
-fi
-
-if [ $ERROR -eq "0" ]; then
-  echo "EXITO: sincronizacion de codigo completa-`date`" >> $status
-fi
+echo "EXITO: sincronizacion de codigo completa-`date`" | tee -a $status
diff --git a/sync/moodledata b/sync/moodledata
--- a/sync/moodledata
+++ b/sync/moodledata
@@ -1,38 +1,35 @@
 #!/bin/bash
-# moodledata : Sincroniza los archivos de los cursos (/var/moodledata/filedir
+# moodledata : Sincroniza los archivos de los cursos (/var/moodledata/filedir)
+
 set -e
 
 moodledata_path="/opt/lampp/moodledata"
 doc_root="/opt/lampp/htdocs"
-
 status="${doc_root}/status/datasync.status"
 
+quitar_bloqueo() {
+  echo "ERROR: PROCESO RSYNC FALLIDO." | tee -a $status
+  /bin/rm -rf /tmp/.rsync.lock
+}
+
+trap quitar_bloqueo ERR
+
+echo "" > $status
+
 if [ -d /tmp/.rsync.lock ]; then
-echo "ERROR: ya existe bloqueo rsync: Quizás hay demasiados datos para descargar. Se reintentará más tarde." > $status
-exit 1
+  echo "ERROR: ya existe bloqueo rsync: Quizás hay demasiados datos para descargar. Se reintentará más tarde." | tee -a $status
+  exit 1
 fi
 
-/bin/mkdir /tmp/.rsync.lock
+echo "Creando bloqueo..." | tee -a $status
+/bin/mkdir -p /tmp/.rsync.lock
 
-if [ $? != "0" ]; then
-echo "ERROR: no se pudo crear bloqueo de descarga rsync" > $status
+echo "===== Beginning rsync =====" | tee -a $status
+nice -n 20 time -f'Tiempo total: %E' /usr/bin/rsync --out-format="%f (%l bytes)" -axvzh --delete -e ssh test.udc.edu.ar:${moodledata_path}/filedir/ ${moodledata_path}/filedir/ >> $status 2>&1
+CODE="$?"
+echo "===== Completed rsync =====" | tee -a $status
+
+echo "Eliminando bloqueo..." | tee -a $status
 /bin/rm -rf /tmp/.rsync.lock
-exit 1
-else
-echo "Bloqueo de descarga creado" > $status
-fi
 
-echo "===== Beginning rsync ====="
-
-nice -n 20 time -f'Tiempo total: %E' /usr/bin/rsync --out-format="%f (%l bytes)" -axvzh --delete -e ssh test.udc.edu.ar:${moodledata_path}/filedir/ ${moodledata_path}/filedir/ > $status 2>&1 
-CODE=$?
-if [ $CODE != "0" ]; then
-echo "ERROR: falló descarga rsync. Revise la salida del comando para solucionar el problema (error $CODE)." >> $status
-/bin/rm -rf /tmp/.rsync.lock
-exit 1
-fi
-
-echo "===== Completed rsync ====="
-
-/bin/rm -rf /tmp/.rsync.lock
-echo "EXITO: sincronizacion moodledata completa-`date`" >> $status
+echo "EXITO: sincronizacion moodledata completa-`date`" | tee -a $status
